### PR TITLE
Replace `gitlike-cli` with `yargs`

### PR DESCRIPTION
**Pull request by gucong3000**
- Replace `gitlike-cli` with `yargs`
- Added: locales for CLI

### CODE REVIEW

**Comment by edi9999** [comment]
+1

Can this be merged soon ? And published to npm ?

**Comment by gucong3000** [comment]
@jedmao Should I merge and publish to npm?

**Comment by jedmao** [comment]
If you want. I think you are the project owner now.

**Comment by gucong3000** [comment]
@edi9999 published.

**Pull request merged**
