### PR TITLE
[wip] Update dependencies

### PR DESCRIPTION
**Pull request by sanemat**
Do not merge this, please.

### CODE REVIEW

**Comment by sanemat** [comment]
This PR passes test, but this doesn't generate d.ts/*d.ts files. I have no ideas.

**Comment by jedmao** [comment]
Is this PR fixing anything? What are you trying to accomplish here?

**Comment by jedmao** [comment]
Are you trying to generate new definitions?

**Comment by sanemat** [comment]
I'm trying to update dependencies. But I'm not familiar with typescript.

**Comment by jedmao** [comment]
The question is why are you trying to update dependencies? Was something not working properly?

**Comment by sanemat** [comment]
Current eclint works fine.
But this depends on some old libraries, e.g. `lodash: ^3.4.0`, `vinyl-fs: ^1.0.0`.
Now, latest is `lodash@4.15.0` and `vinyl-fs@2.4.3`.

I think update dependencies is better.

### One reason

eclint might not work on nodejs v7.
I see this warning during npm install:

```
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
```

`vinyl-fs@1.0.0` depends on `glob-watcher@0.0.8`.
`glob-watcher@0.0.8` depends on, ... `lodash@1.0.2` and `graceful-fs@1.2.3`.

This might not work on nodejs v7.

### Another reason

I use eclint and other libraries.
E.g. eclint and dependencies install `lodash@3.10.0` and `lodash@1.0.2`.
Other libraries use `lodash@4.15.0`.
`npm@>=3` shares libraries which have same version.
If eclint sets `lodash: ^4.0.0` and uses `lodash@4.15.0`, then I use smaller disk space and have shorter install time.

**Pull request closed without merging**
