### PR TITLE
Add support for non doc block comment

### PR DESCRIPTION
**Pull request by gucong3000**
Fixes: #85 
## `eclint.fix`:
input:
```js
/* block
comment */
/*  block
comment */
/*
block
comment
*/
/*
* document
* comment
*/
```
output:
```js
/* block
   comment */
/*  block
    comment */
/*
   block
   comment
 */
/*
 * document
 * comment
 */
```

### CODE REVIEW

**Comment by silverwind** [comment]
I've been testing this, but I can't see a difference.

##### .editorconfig
```ini
root = true

[*]
indent_style = space
indent_size = 2

[*.js]
block_comment_start = /*
block_comment_end = */
```

## test.js
```js
function() {
  /* block
     comment */
  function() {
    /* block
       comment */
    function() {
      /* block
         comment */
    }
  }
}
```
Running `node_modules/eclint/bin/eclint.js check test.js` shows three errors:
```
test.js
    [03:01] ❌️ invalid indent size: 5, expected: 9 (EditorConfig indent_size https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size)
        03|     comment */
    [06:01] ❌️ invalid indent size: 7, expected: 11 (EditorConfig indent_size https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size)
        06|       comment */
    [09:01] ❌️ invalid indent size: 9, expected: 13 (EditorConfig indent_size https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size)
        09|         comment */
```

**Comment by gucong3000** [comment]
@silverwind fixed for your testcase.

**Comment by silverwind** [comment]
Hmm, still won't work for me:

```
$ node_modules/eclint/bin/eclint.js check ectest.js
ectest.js
    [03:01] ❌️ invalid indent size: 5, expected: 6 (EditorConfig indent_size https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size)
        03|     comment */
    [06:01] ❌️ invalid indent size: 7, expected: 8 (EditorConfig indent_size https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size)
        06|       comment */
    [09:01] ❌️ invalid indent size: 9, expected: 10 (EditorConfig indent_size https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size)
        09|         comment */
```
```
$ npm ls eclint                                                                                   1
/Users/silverwind/git/test
└── eclint@2.3.0  (github:jedmao/eclint#ace333f059906f008ae0dfcafc45da51f4253a45)
```

**Comment by gucong3000** [comment]
> Hmm, still won't work for me
There should be no compilation.

**Comment by silverwind** [comment]
Appears so. I just tested against `master` and it now works, thanks!

**Pull request merged**
